config/routes.rb
Rails.application.routes.draw do
  resources :user_rentals, only: [:index, :show, :new, :create, :update]
  resources :rentals, only: [:index, :show, :new, ]
  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental.rb
class Rental < ApplicationRecord
    has_many :user_rentals
    has_many :users, through: :user_rentals
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_rentals
    has_many :rentals, through: :user_rentals
end

app/models/user_rental.rb
class UserRental < ApplicationRecord
    belongs_to :user 
    belongs_to :rental
    accepts_nested_attributes_for :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

    def index
        @rentals = Rental.all
    end

    def show
        @rental = Rental.find(params[:id])
    end

    def new
        
    end
end

app/controllers/user_rentals_controller.rb
class UserRentalsController < ApplicationController
    def index
        @user_rentals = UserRental.all
    end

    def show
        @user_rental = UserRental.find(params[:id])
    end

    def new
        # @rentals = Rental.all
        @user = User.new
        @rental = Rental.find(params[:id])
        @user_rental = UserRental.new

    end

    def create
        @user_rental = UserRental.create(user_rental_params)
        redirect_to rental_path(params[:user_rental][:rental_id])
    end

    def update

    end

    private

    def user_rental_params
        params.require(:user_rental).permit(:start_date, :end_date, :rental_id, :user_id, user_attributes: [:name, :phone])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/user_rentals_helper.rb
module UserRentalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlyNStay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/index.html.erb
<h1>Rental Listings</h1>

<% @rentals.each do |rental| %>
<p> <%=link_to rental.name, rental_path(rental) %></p>
<p> <%=rental.location%></p>
<p> <%=rental.description%></p>
<p> <%=rental.price%>/night</p>
<%end%>

app/views/rentals/new.html.erb
<%=form_for @rental do |f| %>
<%= f.label %>

app/views/rentals/show.html.erb
<h1><%=@rental.name%></h1>

<h2><%=@rental.location%></h2>
<h2>$<%=@rental.price%>/night</h2>
<p> <%=@rental.description%></p>


<%= button_to "Make A New Reservation", new_user_rental_path, method: :get, params: {id: @rental.id}%>

app/views/user_rentals/new.html.erb
<%= form_for @user_rental do |f|%>
<%=f.hidden_field :rental_id, value: @rental.id%>
<%= f.label "Start Date yyyy/mm/dd"%>
<%=f.text_field :start_date%>
<%=f.label "End Date yyyy/mm/dd"%>
<%=f.text_field :end_date%>
<%= f.collection_select(:user_id, User.all, :id, :name, {prompt: "Choose a user"}) %>
<%=f.fields_for :user, @user_rental.build_user do |user_field|%>
<%=user_field.label  "Name" %>
<%=user_field.text_field :name%>
<%=user_field.label "Phone"%>
<%=user_field.text_field :phone%>
<%end%>

<%=f.submit value="create User Rental"%>
<%end%>

app/views/users/index.html.erb
<h1>Users</h1>

<%@users.each do |user|%>
<p><%=link_to user.name, user_path(user)%></p>
<%end%>

app/views/users/show.html.erb
<h1>Welcome <%=@user.name%></h1>





Upcoming Rentals: <%@user.user_rentals.each do |user_rental|%>
                    <%=link_to user_rental.rental.name, rental_path(user_rental.rental)%>
                    <%end%>